version: '3.8'

services:
  srv:
    container_name: server
    build:
      context: ./
      dockerfile: srv.Dockerfile
    ports:
      - "8081:8081"
      - "8082:8082"
    networks:
      - net

#  client:
#    container_name: client
#    depends_on:
#      - srv
#    build:
#      context: ./
#      dockerfile: client.Dockerfile
#    networks:
#      - net

networks:
  net: